// Generated by gencpp from file roborts_msgs/banbuff.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_BANBUFF_H
#define ROBORTS_MSGS_MESSAGE_BANBUFF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct banbuff_
{
  typedef banbuff_<ContainerAllocator> Type;

  banbuff_()
    : banshootbuff_x(0.0)
    , banshootbuff_y(0.0)
    , banmovebuff_x(0.0)
    , banmovebuff_y(0.0)  {
    }
  banbuff_(const ContainerAllocator& _alloc)
    : banshootbuff_x(0.0)
    , banshootbuff_y(0.0)
    , banmovebuff_x(0.0)
    , banmovebuff_y(0.0)  {
  (void)_alloc;
    }



   typedef float _banshootbuff_x_type;
  _banshootbuff_x_type banshootbuff_x;

   typedef float _banshootbuff_y_type;
  _banshootbuff_y_type banshootbuff_y;

   typedef float _banmovebuff_x_type;
  _banmovebuff_x_type banmovebuff_x;

   typedef float _banmovebuff_y_type;
  _banmovebuff_y_type banmovebuff_y;





  typedef boost::shared_ptr< ::roborts_msgs::banbuff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::banbuff_<ContainerAllocator> const> ConstPtr;

}; // struct banbuff_

typedef ::roborts_msgs::banbuff_<std::allocator<void> > banbuff;

typedef boost::shared_ptr< ::roborts_msgs::banbuff > banbuffPtr;
typedef boost::shared_ptr< ::roborts_msgs::banbuff const> banbuffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::banbuff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::banbuff_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::banbuff_<ContainerAllocator1> & lhs, const ::roborts_msgs::banbuff_<ContainerAllocator2> & rhs)
{
  return lhs.banshootbuff_x == rhs.banshootbuff_x &&
    lhs.banshootbuff_y == rhs.banshootbuff_y &&
    lhs.banmovebuff_x == rhs.banmovebuff_x &&
    lhs.banmovebuff_y == rhs.banmovebuff_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::banbuff_<ContainerAllocator1> & lhs, const ::roborts_msgs::banbuff_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::banbuff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::banbuff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::banbuff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::banbuff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::banbuff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::banbuff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::banbuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b73b8e80ff37e35e47cd6cf052eb425";
  }

  static const char* value(const ::roborts_msgs::banbuff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b73b8e80ff37e35ULL;
  static const uint64_t static_value2 = 0xe47cd6cf052eb425ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::banbuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/banbuff";
  }

  static const char* value(const ::roborts_msgs::banbuff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::banbuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 banshootbuff_x\n"
"float32 banshootbuff_y\n"
"\n"
"float32 banmovebuff_x\n"
"float32 banmovebuff_y\n"
;
  }

  static const char* value(const ::roborts_msgs::banbuff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::banbuff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.banshootbuff_x);
      stream.next(m.banshootbuff_y);
      stream.next(m.banmovebuff_x);
      stream.next(m.banmovebuff_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct banbuff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::banbuff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::banbuff_<ContainerAllocator>& v)
  {
    s << indent << "banshootbuff_x: ";
    Printer<float>::stream(s, indent + "  ", v.banshootbuff_x);
    s << indent << "banshootbuff_y: ";
    Printer<float>::stream(s, indent + "  ", v.banshootbuff_y);
    s << indent << "banmovebuff_x: ";
    Printer<float>::stream(s, indent + "  ", v.banmovebuff_x);
    s << indent << "banmovebuff_y: ";
    Printer<float>::stream(s, indent + "  ", v.banmovebuff_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_BANBUFF_H
