// Generated by gencpp from file roborts_msgs/GimbalQuat.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_GIMBALQUAT_H
#define ROBORTS_MSGS_MESSAGE_GIMBALQUAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roborts_msgs
{
template <class ContainerAllocator>
struct GimbalQuat_
{
  typedef GimbalQuat_<ContainerAllocator> Type;

  GimbalQuat_()
    : header()
    , gimbal_quat()  {
      gimbal_quat.assign(0.0);
  }
  GimbalQuat_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gimbal_quat()  {
  (void)_alloc;
      gimbal_quat.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 4>  _gimbal_quat_type;
  _gimbal_quat_type gimbal_quat;





  typedef boost::shared_ptr< ::roborts_msgs::GimbalQuat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::GimbalQuat_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalQuat_

typedef ::roborts_msgs::GimbalQuat_<std::allocator<void> > GimbalQuat;

typedef boost::shared_ptr< ::roborts_msgs::GimbalQuat > GimbalQuatPtr;
typedef boost::shared_ptr< ::roborts_msgs::GimbalQuat const> GimbalQuatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::GimbalQuat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::GimbalQuat_<ContainerAllocator1> & lhs, const ::roborts_msgs::GimbalQuat_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gimbal_quat == rhs.gimbal_quat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::GimbalQuat_<ContainerAllocator1> & lhs, const ::roborts_msgs::GimbalQuat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GimbalQuat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GimbalQuat_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GimbalQuat_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e6f51794ce59bbb7f20132e546ec66d";
  }

  static const char* value(const ::roborts_msgs::GimbalQuat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e6f51794ce59bbbULL;
  static const uint64_t static_value2 = 0x7f20132e546ec66dULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/GimbalQuat";
  }

  static const char* value(const ::roborts_msgs::GimbalQuat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header header\n"
"std_msgs/Header header\n"
"float64[4] gimbal_quat\n"
"# time stamp\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::roborts_msgs::GimbalQuat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gimbal_quat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalQuat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::GimbalQuat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::GimbalQuat_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gimbal_quat[]" << std::endl;
    for (size_t i = 0; i < v.gimbal_quat.size(); ++i)
    {
      s << indent << "  gimbal_quat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gimbal_quat[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_GIMBALQUAT_H
