// Generated by gencpp from file roborts_msgs/ismaster.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_ISMASTER_H
#define ROBORTS_MSGS_MESSAGE_ISMASTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct ismaster_
{
  typedef ismaster_<ContainerAllocator> Type;

  ismaster_()
    : ismaster(false)  {
    }
  ismaster_(const ContainerAllocator& _alloc)
    : ismaster(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ismaster_type;
  _ismaster_type ismaster;





  typedef boost::shared_ptr< ::roborts_msgs::ismaster_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::ismaster_<ContainerAllocator> const> ConstPtr;

}; // struct ismaster_

typedef ::roborts_msgs::ismaster_<std::allocator<void> > ismaster;

typedef boost::shared_ptr< ::roborts_msgs::ismaster > ismasterPtr;
typedef boost::shared_ptr< ::roborts_msgs::ismaster const> ismasterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::ismaster_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::ismaster_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::ismaster_<ContainerAllocator1> & lhs, const ::roborts_msgs::ismaster_<ContainerAllocator2> & rhs)
{
  return lhs.ismaster == rhs.ismaster;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::ismaster_<ContainerAllocator1> & lhs, const ::roborts_msgs::ismaster_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ismaster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ismaster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ismaster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ismaster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ismaster_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ismaster_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::ismaster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ca8b9858ef8af55999571efb5e8c5e0";
  }

  static const char* value(const ::roborts_msgs::ismaster_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ca8b9858ef8af55ULL;
  static const uint64_t static_value2 = 0x999571efb5e8c5e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::ismaster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/ismaster";
  }

  static const char* value(const ::roborts_msgs::ismaster_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::ismaster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ismaster\n"
;
  }

  static const char* value(const ::roborts_msgs::ismaster_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::ismaster_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ismaster);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ismaster_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::ismaster_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::ismaster_<ContainerAllocator>& v)
  {
    s << indent << "ismaster: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ismaster);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_ISMASTER_H
