# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/banbuff.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class banbuff(genpy.Message):
  _md5sum = "6b73b8e80ff37e35e47cd6cf052eb425"
  _type = "roborts_msgs/banbuff"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 banshootbuff_x
float32 banshootbuff_y

float32 banmovebuff_x
float32 banmovebuff_y"""
  __slots__ = ['banshootbuff_x','banshootbuff_y','banmovebuff_x','banmovebuff_y']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       banshootbuff_x,banshootbuff_y,banmovebuff_x,banmovebuff_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(banbuff, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.banshootbuff_x is None:
        self.banshootbuff_x = 0.
      if self.banshootbuff_y is None:
        self.banshootbuff_y = 0.
      if self.banmovebuff_x is None:
        self.banmovebuff_x = 0.
      if self.banmovebuff_y is None:
        self.banmovebuff_y = 0.
    else:
      self.banshootbuff_x = 0.
      self.banshootbuff_y = 0.
      self.banmovebuff_x = 0.
      self.banmovebuff_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.banshootbuff_x, _x.banshootbuff_y, _x.banmovebuff_x, _x.banmovebuff_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.banshootbuff_x, _x.banshootbuff_y, _x.banmovebuff_x, _x.banmovebuff_y,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.banshootbuff_x, _x.banshootbuff_y, _x.banmovebuff_x, _x.banmovebuff_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.banshootbuff_x, _x.banshootbuff_y, _x.banmovebuff_x, _x.banmovebuff_y,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
