# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/DecisionCtrl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DecisionCtrl(genpy.Message):
  _md5sum = "1121754e2c97bc09fdbbef89c270fd04"
  _type = "roborts_msgs/DecisionCtrl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool enable_aim #使能自瞄
float64 offset_angle #发布角度:-80~+80
uint8 can_bullet_num #可发射子弹数量
uint8 robort_behaviour #1:自瞄 2：警戒 3：固定相对角 """
  __slots__ = ['enable_aim','offset_angle','can_bullet_num','robort_behaviour']
  _slot_types = ['bool','float64','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       enable_aim,offset_angle,can_bullet_num,robort_behaviour

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DecisionCtrl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.enable_aim is None:
        self.enable_aim = False
      if self.offset_angle is None:
        self.offset_angle = 0.
      if self.can_bullet_num is None:
        self.can_bullet_num = 0
      if self.robort_behaviour is None:
        self.robort_behaviour = 0
    else:
      self.enable_aim = False
      self.offset_angle = 0.
      self.can_bullet_num = 0
      self.robort_behaviour = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bd2B().pack(_x.enable_aim, _x.offset_angle, _x.can_bullet_num, _x.robort_behaviour))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.enable_aim, _x.offset_angle, _x.can_bullet_num, _x.robort_behaviour,) = _get_struct_Bd2B().unpack(str[start:end])
      self.enable_aim = bool(self.enable_aim)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bd2B().pack(_x.enable_aim, _x.offset_angle, _x.can_bullet_num, _x.robort_behaviour))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.enable_aim, _x.offset_angle, _x.can_bullet_num, _x.robort_behaviour,) = _get_struct_Bd2B().unpack(str[start:end])
      self.enable_aim = bool(self.enable_aim)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bd2B = None
def _get_struct_Bd2B():
    global _struct_Bd2B
    if _struct_Bd2B is None:
        _struct_Bd2B = struct.Struct("<Bd2B")
    return _struct_Bd2B
