# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/glass.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class glass(genpy.Message):
  _md5sum = "a4b75c87961b266016cf3beec4a570f9"
  _type = "roborts_msgs/glass"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64[12] pose_x
float64[12] pose_y"""
  __slots__ = ['pose_x','pose_y']
  _slot_types = ['float64[12]','float64[12]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose_x,pose_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(glass, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pose_x is None:
        self.pose_x = [0.] * 12
      if self.pose_y is None:
        self.pose_y = [0.] * 12
    else:
      self.pose_x = [0.] * 12
      self.pose_y = [0.] * 12

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_12d().pack(*self.pose_x))
      buff.write(_get_struct_12d().pack(*self.pose_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 96
      self.pose_x = _get_struct_12d().unpack(str[start:end])
      start = end
      end += 96
      self.pose_y = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.pose_x.tostring())
      buff.write(self.pose_y.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 96
      self.pose_x = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=12)
      start = end
      end += 96
      self.pose_y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=12)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
