# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/KalmanPlot.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class KalmanPlot(genpy.Message):
  _md5sum = "1f889565f28f759375574e025551dafe"
  _type = "roborts_msgs/KalmanPlot"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 raw_x
float32 raw_y
float32 raw_vx
float32 raw_vy
float32 raw_yaw

float32 kalman_x
float32 kalman_y
float32 kalman_vx
float32 kalman_vy
float32 kalman_yaw"""
  __slots__ = ['raw_x','raw_y','raw_vx','raw_vy','raw_yaw','kalman_x','kalman_y','kalman_vx','kalman_vy','kalman_yaw']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       raw_x,raw_y,raw_vx,raw_vy,raw_yaw,kalman_x,kalman_y,kalman_vx,kalman_vy,kalman_yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KalmanPlot, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.raw_x is None:
        self.raw_x = 0.
      if self.raw_y is None:
        self.raw_y = 0.
      if self.raw_vx is None:
        self.raw_vx = 0.
      if self.raw_vy is None:
        self.raw_vy = 0.
      if self.raw_yaw is None:
        self.raw_yaw = 0.
      if self.kalman_x is None:
        self.kalman_x = 0.
      if self.kalman_y is None:
        self.kalman_y = 0.
      if self.kalman_vx is None:
        self.kalman_vx = 0.
      if self.kalman_vy is None:
        self.kalman_vy = 0.
      if self.kalman_yaw is None:
        self.kalman_yaw = 0.
    else:
      self.raw_x = 0.
      self.raw_y = 0.
      self.raw_vx = 0.
      self.raw_vy = 0.
      self.raw_yaw = 0.
      self.kalman_x = 0.
      self.kalman_y = 0.
      self.kalman_vx = 0.
      self.kalman_vy = 0.
      self.kalman_yaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10f().pack(_x.raw_x, _x.raw_y, _x.raw_vx, _x.raw_vy, _x.raw_yaw, _x.kalman_x, _x.kalman_y, _x.kalman_vx, _x.kalman_vy, _x.kalman_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.raw_x, _x.raw_y, _x.raw_vx, _x.raw_vy, _x.raw_yaw, _x.kalman_x, _x.kalman_y, _x.kalman_vx, _x.kalman_vy, _x.kalman_yaw,) = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10f().pack(_x.raw_x, _x.raw_y, _x.raw_vx, _x.raw_vy, _x.raw_yaw, _x.kalman_x, _x.kalman_y, _x.kalman_vx, _x.kalman_vy, _x.kalman_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.raw_x, _x.raw_y, _x.raw_vx, _x.raw_vy, _x.raw_yaw, _x.kalman_x, _x.kalman_y, _x.kalman_vx, _x.kalman_vy, _x.kalman_yaw,) = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10f = None
def _get_struct_10f():
    global _struct_10f
    if _struct_10f is None:
        _struct_10f = struct.Struct("<10f")
    return _struct_10f
